export const LocalStorageKeys = {
  PlayerId: 'playerid',
  IsHost: 'ishost',
  Score: 'score',
  GameId: 'gameid',
  Username: 'username',
  ChatRoomData: 'chatroomdata',
  PlayersList: 'playerslist',
  Guesses: 'guesses',
  CurrentGuess: 'currentguess',
  FinalScores: 'finalscores',
  WinningUsername: 'winningusername',
  HighScore: 'highscore',
  WordsMap: 'wordsmap',
};
