/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-group-wordle-BmPtPdtO6HrW3Cnk8SerUQz5gx3Bgbq1",
  "version": "2020-11-20"
}

export default ebconfig;