/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-serverless-database-app-UdKydLMQxW3yZ998VtZlt-YMDWnuCRn7",
  "version": "2020-11-20"
}

export default ebconfig;